[[plugins]]
repo = 'ryanoasis/vim-devicons'

repo = 'psf/black'

# # [[plugins]]
# # repo = 'davidhalter/jedi-vim'
# # hook_add = '''
# # let g:jedi#goto_command = "<leader>d"
# # let g:jedi#goto_assignments_command = "<leader>g"
# # let g:jedi#goto_definitions_command = ""
# # let g:jedi#documentation_command = "K"
# # let g:jedi#usages_command = "<leader>n"
# # let g:jedi#completions_command = "<C-Space>"
# # let g:jedi#rename_command = "<leader>r"
# # let g:jedi#smart_auto_mappings = 1
# # '''
# 
# # [[plugins]]
# # repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
  \ 'colorscheme': 'landscape',
  \ 'active': {
  \   'left': [
  \     ['mode', 'paste'],
  \     ['gitbranch', 'readonly', 'filename', 'modified'],
  \   ],
  \   'right': [
  \     ['lineinfo', 'syntastic'],
  \     ['percent'],
  \     ['charcode', 'fileformat', 'fileencoding', 'filetype'],
  \   ]
  \ },
  \ 'component_function': {
  \   'gitbranch': 'fugitive#head',
  \   'syntastic': 'SyntasticStatuslineFlag',
  \ },
  \ 'component_expand': {
  \   'syntastic': 'SyntasticStatuslineFlag',
  \ },
  \ 'component_type': {
  \   'syntastic': 'error',
  \ },
  \ }
let g:syntastic_mode_map = { 'mode': 'passive',
      \                      'active_filetypes': ['c', 'cpp'] }
augroup AutoSyntastic
  autocmd!
  autocmd BufWritePost *.c,*.cpp call s:syntastic()
augroup END
function! s:syntastic()
  SyntasticCheck
  call lightline#update()
endfunction
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tomasr/molokai'

# make git convinient
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_sign_added = '✚'
let g:gitgutter_sign_modified = '➜'
let g:gitgutter_sign_removed = '✘'
let g:gitgutter_max_signs = 500
let s:gitgutter_was_enabled = gitgutter#utility#getbufvar(bufnr(''), 'enabled')
'''

# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_add = '''
# let g:ale_sign_error = '☓'
# let g:ale_sign_warning = '⚠'
# 
# " ロケーションリストの代わりにQuickFixを使用する
# let g:ale_set_loclist = 0
# let g:ale_set_quickfix = 1
# 
# " エラーと警告の一覧を見るためにウィンドウを開いておきたい
# "let g:ale_open_list = 1
# " エラーと警告がなくなっても開いたままにする
# "let g:ale_keep_list_window_open = 1
# 
# let g:ale_linters = {
#     \ 'python': ['python', 'flake8', 'pylint'],
#     \ 'php': ['phpcs'],
#     \ }
# 
# " 各ツールをFixerとして登録
# " 'python': ['autopep8', 'yapf', 'isort'],
# let g:ale_fixers = {
#     \ 'python': [
# 	\    {buffer, lines -> {'command': 'yapf $%t -i --style="{indent_dictionary_value=True}" && isort -sl %t;', 'read_temporary_file': 1}}
# 	\ ],
#     \ }
# "let g:ale_fix_on_save = 1
# 
# let g:ale_php_phpcs_standard = 'WordPress'
# "let g:ale_statusline_format = ['E%d', 'W%d', '']
# '''

[[plugins]]
repo = 'cohama/agit.vim'
hook_add = '''
autocmd FileType agit call s:my_agit_setting()
function! s:my_agit_setting()
  nmap <buffer> ch <Plug>(agit-git-cherry-pick)
  nmap <buffer> Rv <Plug>(agit-git-revert)
endfunction
'''

[[plugins]]
repo = 'rhysd/conflict-marker.vim'


[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = "aklt/plantuml-syntax"


[[plugins]]
repo = "majutsushi/tagbar"

[[plugins]]
repo = "posva/vim-vue"

[[plugins]]
repo = "rainglow/vim"

[[plugins]]
repo = "neoclide/coc.nvim"
build = './install.sh nightly'
hook_add = '''
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()
""" <Tab>で次、<S+Tab>で前
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
'''

# ------ FileExploler関連---------
[[plugins]]
repo = "Shougo/defx.nvim"
hook_add = '''
autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  " Define mappings
  nnoremap <silent><buffer><expr> <CR>
  \ defx#do_action('drop', 'vsplit')
  nnoremap <silent><buffer><expr> c
  \ defx#do_action('copy')
  nnoremap <silent><buffer><expr> r
  \ defx#do_action('move')
  nnoremap <silent><buffer><expr> p
  \ defx#do_action('paste')
  nnoremap <silent><buffer><expr> l
  \ defx#do_action('open')
  nnoremap <silent><buffer><expr> E
  \ defx#do_action('multi', [['drop', 'vsplit'], 'quit'])
  nnoremap <silent><buffer><expr> P
  \ defx#do_action('open', 'pedit')
  nnoremap <silent><buffer><expr> o
  \ defx#do_action('open_or_close_tree')
  nnoremap <silent><buffer><expr> O
  \ defx#do_action('open_tree_recursive')
  nnoremap <silent><buffer><expr> A
  \ defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> a
  \ defx#do_action('new_file')
  nnoremap <silent><buffer><expr> C
  \ defx#do_action('toggle_columns',
  \                'mark:indent:icon:filename:type:size:time')
  nnoremap <silent><buffer><expr> S
  \ defx#do_action('toggle_sort', 'time')
  nnoremap <silent><buffer><expr> d
  \ defx#do_action('remove')
  nnoremap <silent><buffer><expr> r
  \ defx#do_action('rename')
  nnoremap <silent><buffer><expr> yy
  \ defx#do_action('yank_path')
  nnoremap <silent><buffer><expr> .
  \ defx#do_action('toggle_ignored_files')
  nnoremap <silent><buffer><expr> ;
  \ defx#do_action('repeat')
  nnoremap <silent><buffer><expr> h
  \ defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> ~
  \ defx#do_action('cd')
  nnoremap <silent><buffer><expr> q
  \ defx#do_action('quit')
  nnoremap <silent><buffer><expr> <Space>
  \ defx#do_action('toggle_select') . 'j'
  nnoremap <silent><buffer><expr> *
  \ defx#do_action('toggle_select_all')
  nnoremap <silent><buffer><expr> j
  \ line('.') == line('$') ? 'gg' : 'j'
  nnoremap <silent><buffer><expr> k
  \ line('.') == 1 ? 'G' : 'k'
  nnoremap <silent><buffer><expr> <C-l>
  \ defx#do_action('redraw')
  nnoremap <silent><buffer><expr> <C-g>
  \ defx#do_action('print')
  nnoremap <silent><buffer><expr> cd
  \ defx#do_action('change_vim_cwd')
  nnoremap <silent><buffer><expr> t
  \ defx#do_action('open','tabnew')
endfunction
nmap <C-n> :Defx -resume -toggle -winwidth=30 -split=vertical -direction=topleft -listed -ignored-files=__pycache__,.mypy_cache,*.pyc<CR>
'''
# ------ FileExploler関連---------

[[plugins]]
repo = 'github/copilot.vim'



[[plugins]]
repo = 'kyoh86/vim-ripgrep'
hook_add = '''
command! -nargs=* -complete=file Ripgrep :call ripgrep#search(<q-args>)
'''


# telescope.nvimが依存
[[plugins]]
repo = 'nvim-lua/plenary.nvim'


[[plugins]]
depends = ['airblade/vim-rooter']
hook_add = '''
" Search for Project root
" Find files using Telescope command-line sugar.
nnoremap <C-p> <cmd>Telescope find_files<cr>
nnoremap <C-g> <cmd>Telescope live_grep<cr>
nnoremap <C-b> <cmd>Telescope buffers<cr>
" プロジェクトルートではなく現在開いているファイルを起点にファイル検索
nnoremap <M-p> <cmd>lua require('telescope.builtin').find_files( { cwd = vim.fn.expand('%:p:h') })<cr>
nnoremap <M-g> <cmd>lua require('telescope.builtin').live_grep( { cwd = vim.fn.expand('%:p:h') })<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>

" Using Lua functions
nnoremap <leader>ff <cmd>lua require('telescope.builtin').find_files()<cr>
nnoremap <leader>fg <cmd>lua require('telescope.builtin').live_grep()<cr>
nnoremap <leader>fb <cmd>lua require('telescope.builtin').buffers()<cr>
nnoremap <leader>fh <cmd>lua require('telescope.builtin').help_tags()<cr>
lua <<EOF
require('telescope').setup{
  defaults = {
    mappings = {
      n = {
        ["<esc>"] = require('telescope.actions').close,
      },
      i = {
        ["<esc>"] = require('telescope.actions').close,
        ["<C-a>"] = require('telescope.actions').send_to_qflist + require('telescope.actions').open_qflist,
        ["<C-q>"] = require('telescope.actions').send_selected_to_qflist + require('telescope.actions').open_qflist
      }
    }
  }
}
EOF
'''
repo = 'nvim-telescope/telescope.nvim'

# telescope-frequencyが依存
[[plugins]]
repo = 'tami5/sqlite.lua'

# telescope-frequencyが依存
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
hook_add = '''
nnoremap <C-h> <cmd>Telescope frecency<cr>
lua << EOF
require"telescope".load_extension("frecency")
EOF

augroup vimrc_telescope_frecency
  autocmd!
  autocmd VimEnter * lua require('telescope').extensions.frecency.frecency()
augroup END
'''
repo = 'nvim-telescope/telescope-frecency.nvim'



[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
let g:go_metalinter_command='golangci-lint'
nnoremap <C-E> :GoReferrers<CR>
'''
