[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#hook_add = 'let g:deoplete#enable_at_startup = 1'
#depends = 'context_filetype.vim'
#if = '''has('nvim')'''
#on_event = 'InsertCharPre'
#on_i = 1
#hook_source = '''
#let g:deoplete#enable_at_startup = 1
#'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''


[[plugins]]
repo = 'cespare/vim-toml'


[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'rhysd/nyaovim-markdown-preview'
[[plugins]]
repo = 'yaasita/ore_markdown'
[[plugins]]
repo = 'mattn/emmet-vim'



[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#[[plugins]]
#repo = 'Shougo/neocomplete.vim'
